version: '2.0'
services:
  web:
    container_name: odoo12
    image: odoo:12
    depends_on:
      - db10
    ports:
      - 9091:8069
    volumes:
      - odoo12-web-data:/var/lib/odoo
      - ./:/etc/odoo/
      - ./../addons:/mnt/extra-addons
    entrypoint: "/entrypoint.sh --update saldoapp"
  db10:
    container_name: postgres10
    image: postgres:10.0
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo12-db-data2:/var/lib/postgresql/data/pgdata

volumes:
  odoo12-web-data:
  odoo12-db-data2: